# Generated by Django 5.1.1 on 2025-01-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gyms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gym",
            name="first_prise",
            field=models.IntegerField(default=50),
        ),
    ]
